### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by benkonrath**
I'm using this library in a project and I needed to fix some issues to get everything to work. This PR includes the changes from #13 and #15.

### CODE REVIEW

**Comment by benkonrath** [comment]
I just pushed a few more changes: Fixed a bug, updated the code for Python 3 and updated the travis config so the tests pass.

**Comment by arjan-s** [comment]
I don't think mhogerheijde is still around :(

**Comment by mhogerheijde** [comment]
Sorry to be (very) late with my response: I'm not working on this project anymore, it's open & free in every sense of the word, so feel free to take from it what you need.

**Comment by benkonrath** [comment]
@mhogerheijde Could you transfer this project to my github account (benkonrath)? I'd like to take over maintaining this package. Thanks.

**Comment by benkonrath** [comment]
@mhogerheijde I just saw your change to the README. If you prefer to keep hosting this repo, that's also fine. Just let me know and I'll create a repo for you to point to in my account. Thanks.

**Comment by mhogerheijde** [comment]
I'd like to have a copy somewhere :) but transferring ownership is fine :+1: I'll clone it back ;)

**Comment by mhogerheijde** [comment]
Seems it worked! :) Happy coding :tada:

**Comment by benkonrath** [comment]
@mhogerheijde Thanks!

**Comment by benkonrath** [comment]
This has been merged to develop.

**Pull request closed without merging**
